# Importing required libraries

In [425]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt

# Reading CSV file

In [426]:
data=pd.read_csv("C:\\Users\\Saikian\\Desktop\\Social_Network_Ads.csv")

In [427]:
data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617482    Male   45            26000          1
18   15704583    Male   46            28000          1
19   15621083  Female   48            29000          1
20   15649487    Male   45            22000          1
21   15736760  Female   47            49000          1
22   15714658    Male   48            41000          1
23   15599081  Female   45            22000          1
24   15705113    Male   46            23000          1
25   15631159    Male   47            20000          1
26   15792818    Male   49            28000          1
27   15633531  Female   47            30000          1
28   15744529    Male   29            43000          0
29   15669656    Male   31            18000          0
..        ...     ...  ...              ...        ...
370  15611430  Female   60            46000          1
371  15774744    Male   60            83000          1
372  15629885  Female   39            73000          0
373  15708791    Male   59           130000          1
374  15793890  Female   37            80000          0
375  15646091  Female   46            32000          1
376  15596984  Female   46            74000          0
377  15800215  Female   42            53000          0
378  15577806    Male   41            87000          1
379  15749381  Female   58            23000          1
380  15683758    Male   42            64000          0
381  15670615    Male   48            33000          1
382  15715622  Female   44           139000          1
383  15707634    Male   49            28000          1
384  15806901  Female   57            33000          1
385  15775335    Male   56            60000          1
386  15724150  Female   49            39000          1
387  15627220    Male   39            71000          0
388  15672330    Male   47            34000          1
389  15668521  Female   48            35000          1
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

# Filtering required columns

In [428]:
x=data.iloc[:,[2,3]].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [429]:
y=data.iloc[:,4].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

# Train & Test the Dataset

In [430]:
from sklearn.model_selection import train_test_split

In [431]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [432]:
x_train

array([[    36,  99000],
       [    49,  36000],
       [    48,  74000],
       [    55, 130000],
       [    38,  65000],
       [    41,  72000],
       [    40,  71000],
       [    22,  27000],
       [    55, 125000],
       [    40,  57000],
       [    57,  33000],
       [    58,  38000],
       [    49,  74000],
       [    35, 108000],
       [    39, 134000],
       [    52, 150000],
       [    42,  54000],
       [    42, 108000],
       [    58, 144000],
       [    51,  23000],
       [    39,  42000],
       [    30,  79000],
       [    40,  75000],
       [    37,  71000],
       [    41,  51000],
       [    24,  58000],
       [    45,  45000],
       [    36,  63000],
       [    19,  21000],
       [    57,  74000],
       [    34,  25000],
       [    33,  69000],
       [    36,  52000],
       [    40,  78000],
       [    41,  52000],
       [    50,  20000],
       [    27, 137000],
       [    41,  60000],
       [    35,  73000],
       [    55,  39000],


In [433]:
x_test

array([[    35,  23000],
       [    29,  43000],
       [    41,  63000],
       [    41,  87000],
       [    28,  85000],
       [    29,  80000],
       [    31,  76000],
       [    60,  46000],
       [    36, 144000],
       [    29,  43000],
       [    20,  82000],
       [    45,  22000],
       [    35,  53000],
       [    38, 113000],
       [    39,  61000],
       [    18,  68000],
       [    47,  49000],
       [    30,  80000],
       [    35,  61000],
       [    49,  88000],
       [    31, 118000],
       [    25,  80000],
       [    32, 117000],
       [    37,  75000],
       [    59, 143000],
       [    27,  84000],
       [    42,  80000],
       [    35,  39000],
       [    36,  54000],
       [    39,  71000],
       [    22,  55000],
       [    41,  72000],
       [    52, 114000],
       [    43, 133000],
       [    39,  42000],
       [    52,  90000],
       [    56, 104000],
       [    23,  82000],
       [    27,  57000],
       [    37,  53000],


In [434]:
y_train.shape

(300,)

In [435]:
y_test.shape

(100,)

# Normalisation

In [436]:
from sklearn.preprocessing import StandardScaler

In [437]:
sc=StandardScaler()

In [438]:
x_train=sc.fit_transform(x_train)

In [439]:
x_train

array([[-0.18309621,  0.86971299],
       [ 1.06966733, -0.9664773 ],
       [ 0.97330091,  0.14106605],
       [ 1.64786589,  1.77323519],
       [ 0.00963664, -0.12124685],
       [ 0.29873592,  0.08277429],
       [ 0.2023695 ,  0.05362841],
       [-1.53222618, -1.2287902 ],
       [ 1.64786589,  1.6275058 ],
       [ 0.2023695 , -0.35441387],
       [ 1.84059875, -1.05391493],
       [ 1.93696517, -0.90818554],
       [ 1.06966733,  0.14106605],
       [-0.27946264,  1.13202588],
       [ 0.10600307,  1.8898187 ],
       [ 1.35876661,  2.35615274],
       [ 0.39510235, -0.4418515 ],
       [ 0.39510235,  1.13202588],
       [ 1.93696517,  2.18127748],
       [ 1.26240019, -1.34537371],
       [ 0.10600307, -0.79160203],
       [-0.76129477,  0.28679544],
       [ 0.2023695 ,  0.17021192],
       [-0.08672978,  0.05362841],
       [ 0.29873592, -0.52928914],
       [-1.33949333, -0.32526799],
       [ 0.68420163, -0.7041644 ],
       [-0.18309621, -0.17953861],
       [-1.82132546,

In [440]:
x_test=sc.transform(x_test)

In [441]:
x_test

array([[-0.27946264, -1.34537371],
       [-0.8576612 , -0.76245616],
       [ 0.29873592, -0.17953861],
       [ 0.29873592,  0.51996246],
       [-0.95402762,  0.4616707 ],
       [-0.8576612 ,  0.31594131],
       [-0.66492834,  0.1993578 ],
       [ 2.12969803, -0.67501852],
       [-0.18309621,  2.18127748],
       [-0.8576612 , -0.76245616],
       [-1.72495903,  0.37423307],
       [ 0.68420163, -1.37451959],
       [-0.27946264, -0.47099738],
       [ 0.00963664,  1.27775527],
       [ 0.10600307, -0.23783036],
       [-1.91769189, -0.03380922],
       [ 0.87693448, -0.58758089],
       [-0.76129477,  0.31594131],
       [-0.27946264, -0.23783036],
       [ 1.06966733,  0.54910833],
       [-0.66492834,  1.42348466],
       [-1.2431269 ,  0.31594131],
       [-0.56856192,  1.39433878],
       [-0.08672978,  0.17021192],
       [ 2.0333316 ,  2.1521316 ],
       [-1.05039405,  0.43252482],
       [ 0.39510235,  0.31594131],
       [-0.27946264, -0.87903967],
       [-0.18309621,

# Model building

In [442]:
from sklearn.neighbors import KNeighborsClassifier

In [443]:
classifier=KNeighborsClassifier(n_neighbors =5, metric='minkowski')

In [444]:
classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [445]:
y_pred=classifier.predict(x_test)

In [446]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0], dtype=int64)

In [447]:
y_test

array([0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0], dtype=int64)

In [448]:
from sklearn.metrics import confusion_matrix

In [449]:
cm=confusion_matrix(y_test,y_pred)

In [450]:
cm

array([[61,  4],
       [ 3, 32]], dtype=int64)

In [451]:
(61+32)/(61+32+4+3)

0.93

# Finally Accuracy is 93%